# Generated by Django 3.0.7 on 2020-07-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='wesite',
            field=models.CharField(default='', max_length=122),
        ),
    ]
