# Generated by Django 3.0.7 on 2020-07-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_wesite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='wesite',
        ),
    ]
