# Generated by Django 3.0.7 on 2020-07-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200710_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(default='', max_length=12)),
                ('address', models.CharField(default='', max_length=122)),
                ('review', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
